apiVersion: v1
kind: Service
metadata:
  name: springboot-app-service-loadbalancer
spec:
  selector:
    app: springboot-app
  ports:
    - protocol: TCP
      port: 80   # 외부에서 접근할 포트
      targetPort: 8089  # 컨테이너 내 Spring Boot 포트
  type: LoadBalancer  # 외부 IP 할당
