apiVersion: v1
kind: Service
metadata:
  name: springboot-app-service-nodeport
spec:
  selector:
    app: springboot-app
  ports:
    - protocol: TCP
      port: 80    # 외부에서 접근할 포트
      targetPort: 8089  # 컨테이너 내 포트
      nodePort: 30001  # 노드의 포트 (외부에서 접근할 수 있게 설정)
  type: NodePort   # 로컬 클러스터 외부 접근
